project:
  output-dir: .
  type: website

website:
  title: "showmaker"
  navbar:
    left:
      - href: index.qmd
        text: Get started

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
